// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] s_av_cpu_mem_address_i,
    input   [3:0] s_av_cpu_mem_byteenable_i,
    input         s_av_cpu_mem_read_i,
    input   [7:0] s_av_cpu_mem_burstcount_i,
    input         s_av_cpu_mem_write_i,
    input  [31:0] s_av_cpu_mem_writedata_i,
    output [31:0] s_av_cpu_mem_readdata_o,
    output        s_av_cpu_mem_waitrequest_o,
    output        s_av_cpu_mem_readdatavalid_o,
    input  [31:0] s_av_cpu_io_address_i,
    input   [3:0] s_av_cpu_io_byteenable_i,
    input         s_av_cpu_io_read_i,
    input   [7:0] s_av_cpu_io_burstcount_i,
    input         s_av_cpu_io_write_i,
    input  [31:0] s_av_cpu_io_writedata_i,
    output [31:0] s_av_cpu_io_readdata_o,
    output        s_av_cpu_io_waitrequest_o,
    output        s_av_cpu_io_readdatavalid_o,
    output [31:0] wb_bootrom_mem_adr_o,
    output [31:0] wb_bootrom_mem_dat_o,
    output  [3:0] wb_bootrom_mem_sel_o,
    output        wb_bootrom_mem_we_o,
    output        wb_bootrom_mem_cyc_o,
    output        wb_bootrom_mem_stb_o,
    output  [2:0] wb_bootrom_mem_cti_o,
    output  [1:0] wb_bootrom_mem_bte_o,
    input  [31:0] wb_bootrom_mem_dat_i,
    input         wb_bootrom_mem_ack_i,
    input         wb_bootrom_mem_err_i,
    input         wb_bootrom_mem_rty_i,
    output [31:0] wb_mon88_mem_adr_o,
    output [31:0] wb_mon88_mem_dat_o,
    output  [3:0] wb_mon88_mem_sel_o,
    output        wb_mon88_mem_we_o,
    output        wb_mon88_mem_cyc_o,
    output        wb_mon88_mem_stb_o,
    output  [2:0] wb_mon88_mem_cti_o,
    output  [1:0] wb_mon88_mem_bte_o,
    input  [31:0] wb_mon88_mem_dat_i,
    input         wb_mon88_mem_ack_i,
    input         wb_mon88_mem_err_i,
    input         wb_mon88_mem_rty_i,
    output [31:0] wb_uart_io_adr_o,
    output [15:0] wb_uart_io_dat_o,
    output  [3:0] wb_uart_io_sel_o,
    output        wb_uart_io_we_o,
    output        wb_uart_io_cyc_o,
    output        wb_uart_io_stb_o,
    output  [2:0] wb_uart_io_cti_o,
    output  [1:0] wb_uart_io_bte_o,
    input  [15:0] wb_uart_io_dat_i,
    input         wb_uart_io_ack_i,
    input         wb_uart_io_err_i,
    input         wb_uart_io_rty_i,
    output [31:0] wb_post_io_adr_o,
    output [15:0] wb_post_io_dat_o,
    output  [3:0] wb_post_io_sel_o,
    output        wb_post_io_we_o,
    output        wb_post_io_cyc_o,
    output        wb_post_io_stb_o,
    output  [2:0] wb_post_io_cti_o,
    output  [1:0] wb_post_io_bte_o,
    input  [15:0] wb_post_io_dat_i,
    input         wb_post_io_ack_i,
    input         wb_post_io_err_i,
    input         wb_post_io_rty_i);

wire [31:0] wb_m2s_cpu_mem_adr;
wire [31:0] wb_m2s_cpu_mem_dat;
wire  [3:0] wb_m2s_cpu_mem_sel;
wire        wb_m2s_cpu_mem_we;
wire        wb_m2s_cpu_mem_cyc;
wire        wb_m2s_cpu_mem_stb;
wire  [2:0] wb_m2s_cpu_mem_cti;
wire  [1:0] wb_m2s_cpu_mem_bte;
wire [31:0] wb_s2m_cpu_mem_dat;
wire        wb_s2m_cpu_mem_ack;
wire        wb_s2m_cpu_mem_err;
wire        wb_s2m_cpu_mem_rty;
wire [31:0] wb_m2s_cpu_io_adr;
wire [31:0] wb_m2s_cpu_io_dat;
wire  [3:0] wb_m2s_cpu_io_sel;
wire        wb_m2s_cpu_io_we;
wire        wb_m2s_cpu_io_cyc;
wire        wb_m2s_cpu_io_stb;
wire  [2:0] wb_m2s_cpu_io_cti;
wire  [1:0] wb_m2s_cpu_io_bte;
wire [31:0] wb_s2m_cpu_io_dat;
wire        wb_s2m_cpu_io_ack;
wire        wb_s2m_cpu_io_err;
wire        wb_s2m_cpu_io_rty;
wire [31:0] wb_m2s_resize_uart_io_adr;
wire [31:0] wb_m2s_resize_uart_io_dat;
wire  [3:0] wb_m2s_resize_uart_io_sel;
wire        wb_m2s_resize_uart_io_we;
wire        wb_m2s_resize_uart_io_cyc;
wire        wb_m2s_resize_uart_io_stb;
wire  [2:0] wb_m2s_resize_uart_io_cti;
wire  [1:0] wb_m2s_resize_uart_io_bte;
wire [31:0] wb_s2m_resize_uart_io_dat;
wire        wb_s2m_resize_uart_io_ack;
wire        wb_s2m_resize_uart_io_err;
wire        wb_s2m_resize_uart_io_rty;
wire [31:0] wb_m2s_resize_post_io_adr;
wire [31:0] wb_m2s_resize_post_io_dat;
wire  [3:0] wb_m2s_resize_post_io_sel;
wire        wb_m2s_resize_post_io_we;
wire        wb_m2s_resize_post_io_cyc;
wire        wb_m2s_resize_post_io_stb;
wire  [2:0] wb_m2s_resize_post_io_cti;
wire  [1:0] wb_m2s_resize_post_io_bte;
wire [31:0] wb_s2m_resize_post_io_dat;
wire        wb_s2m_resize_post_io_ack;
wire        wb_s2m_resize_post_io_err;
wire        wb_s2m_resize_post_io_rty;

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h000fc000, 32'h000dc000}),
    .MATCH_MASK ({32'hffffc000, 32'hffffc000}))
 wb_mux_cpu_mem
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_m2s_cpu_mem_adr),
    .wbm_dat_i (wb_m2s_cpu_mem_dat),
    .wbm_sel_i (wb_m2s_cpu_mem_sel),
    .wbm_we_i  (wb_m2s_cpu_mem_we),
    .wbm_cyc_i (wb_m2s_cpu_mem_cyc),
    .wbm_stb_i (wb_m2s_cpu_mem_stb),
    .wbm_cti_i (wb_m2s_cpu_mem_cti),
    .wbm_bte_i (wb_m2s_cpu_mem_bte),
    .wbm_dat_o (wb_s2m_cpu_mem_dat),
    .wbm_ack_o (wb_s2m_cpu_mem_ack),
    .wbm_err_o (wb_s2m_cpu_mem_err),
    .wbm_rty_o (wb_s2m_cpu_mem_rty),
    .wbs_adr_o ({wb_bootrom_mem_adr_o, wb_mon88_mem_adr_o}),
    .wbs_dat_o ({wb_bootrom_mem_dat_o, wb_mon88_mem_dat_o}),
    .wbs_sel_o ({wb_bootrom_mem_sel_o, wb_mon88_mem_sel_o}),
    .wbs_we_o  ({wb_bootrom_mem_we_o, wb_mon88_mem_we_o}),
    .wbs_cyc_o ({wb_bootrom_mem_cyc_o, wb_mon88_mem_cyc_o}),
    .wbs_stb_o ({wb_bootrom_mem_stb_o, wb_mon88_mem_stb_o}),
    .wbs_cti_o ({wb_bootrom_mem_cti_o, wb_mon88_mem_cti_o}),
    .wbs_bte_o ({wb_bootrom_mem_bte_o, wb_mon88_mem_bte_o}),
    .wbs_dat_i ({wb_bootrom_mem_dat_i, wb_mon88_mem_dat_i}),
    .wbs_ack_i ({wb_bootrom_mem_ack_i, wb_mon88_mem_ack_i}),
    .wbs_err_i ({wb_bootrom_mem_err_i, wb_mon88_mem_err_i}),
    .wbs_rty_i ({wb_bootrom_mem_rty_i, wb_mon88_mem_rty_i}));

avalon_to_wb_bridge
  #(.AW (32),
    .DW (32))
 avalon_to_wb_bridge_cpu_mem
   (.wb_clk_i             (wb_clk_i),
    .wb_rst_i             (wb_rst_i),
    .wbm_adr_o            (wb_m2s_cpu_mem_adr),
    .wbm_dat_o            (wb_m2s_cpu_mem_dat),
    .wbm_sel_o            (wb_m2s_cpu_mem_sel),
    .wbm_we_o             (wb_m2s_cpu_mem_we),
    .wbm_cyc_o            (wb_m2s_cpu_mem_cyc),
    .wbm_stb_o            (wb_m2s_cpu_mem_stb),
    .wbm_cti_o            (wb_m2s_cpu_mem_cti),
    .wbm_bte_o            (wb_m2s_cpu_mem_bte),
    .wbm_dat_i            (wb_s2m_cpu_mem_dat),
    .wbm_ack_i            (wb_s2m_cpu_mem_ack),
    .wbm_err_i            (wb_s2m_cpu_mem_err),
    .wbm_rty_i            (wb_s2m_cpu_mem_rty),
    .s_av_address_i       (s_av_cpu_mem_address_i),
    .s_av_byteenable_i    (s_av_cpu_mem_byteenable_i),
    .s_av_read_i          (s_av_cpu_mem_read_i),
    .s_av_burstcount_i    (s_av_cpu_mem_burstcount_i),
    .s_av_write_i         (s_av_cpu_mem_write_i),
    .s_av_writedata_i     (s_av_cpu_mem_writedata_i),
    .s_av_readdata_o      (s_av_cpu_mem_readdata_o),
    .s_av_waitrequest_o   (s_av_cpu_mem_waitrequest_o),
    .s_av_readdatavalid_o (s_av_cpu_mem_readdatavalid_o));

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h000003f8, 32'h00000080}),
    .MATCH_MASK ({32'hfffffff8, 32'hffffffff}))
 wb_mux_cpu_io
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_m2s_cpu_io_adr),
    .wbm_dat_i (wb_m2s_cpu_io_dat),
    .wbm_sel_i (wb_m2s_cpu_io_sel),
    .wbm_we_i  (wb_m2s_cpu_io_we),
    .wbm_cyc_i (wb_m2s_cpu_io_cyc),
    .wbm_stb_i (wb_m2s_cpu_io_stb),
    .wbm_cti_i (wb_m2s_cpu_io_cti),
    .wbm_bte_i (wb_m2s_cpu_io_bte),
    .wbm_dat_o (wb_s2m_cpu_io_dat),
    .wbm_ack_o (wb_s2m_cpu_io_ack),
    .wbm_err_o (wb_s2m_cpu_io_err),
    .wbm_rty_o (wb_s2m_cpu_io_rty),
    .wbs_adr_o ({wb_m2s_resize_uart_io_adr, wb_m2s_resize_post_io_adr}),
    .wbs_dat_o ({wb_m2s_resize_uart_io_dat, wb_m2s_resize_post_io_dat}),
    .wbs_sel_o ({wb_m2s_resize_uart_io_sel, wb_m2s_resize_post_io_sel}),
    .wbs_we_o  ({wb_m2s_resize_uart_io_we, wb_m2s_resize_post_io_we}),
    .wbs_cyc_o ({wb_m2s_resize_uart_io_cyc, wb_m2s_resize_post_io_cyc}),
    .wbs_stb_o ({wb_m2s_resize_uart_io_stb, wb_m2s_resize_post_io_stb}),
    .wbs_cti_o ({wb_m2s_resize_uart_io_cti, wb_m2s_resize_post_io_cti}),
    .wbs_bte_o ({wb_m2s_resize_uart_io_bte, wb_m2s_resize_post_io_bte}),
    .wbs_dat_i ({wb_s2m_resize_uart_io_dat, wb_s2m_resize_post_io_dat}),
    .wbs_ack_i ({wb_s2m_resize_uart_io_ack, wb_s2m_resize_post_io_ack}),
    .wbs_err_i ({wb_s2m_resize_uart_io_err, wb_s2m_resize_post_io_err}),
    .wbs_rty_i ({wb_s2m_resize_uart_io_rty, wb_s2m_resize_post_io_rty}));

avalon_to_wb_bridge
  #(.AW (32),
    .DW (32))
 avalon_to_wb_bridge_cpu_io
   (.wb_clk_i             (wb_clk_i),
    .wb_rst_i             (wb_rst_i),
    .wbm_adr_o            (wb_m2s_cpu_io_adr),
    .wbm_dat_o            (wb_m2s_cpu_io_dat),
    .wbm_sel_o            (wb_m2s_cpu_io_sel),
    .wbm_we_o             (wb_m2s_cpu_io_we),
    .wbm_cyc_o            (wb_m2s_cpu_io_cyc),
    .wbm_stb_o            (wb_m2s_cpu_io_stb),
    .wbm_cti_o            (wb_m2s_cpu_io_cti),
    .wbm_bte_o            (wb_m2s_cpu_io_bte),
    .wbm_dat_i            (wb_s2m_cpu_io_dat),
    .wbm_ack_i            (wb_s2m_cpu_io_ack),
    .wbm_err_i            (wb_s2m_cpu_io_err),
    .wbm_rty_i            (wb_s2m_cpu_io_rty),
    .s_av_address_i       (s_av_cpu_io_address_i),
    .s_av_byteenable_i    (s_av_cpu_io_byteenable_i),
    .s_av_read_i          (s_av_cpu_io_read_i),
    .s_av_burstcount_i    (s_av_cpu_io_burstcount_i),
    .s_av_write_i         (s_av_cpu_io_write_i),
    .s_av_writedata_i     (s_av_cpu_io_writedata_i),
    .s_av_readdata_o      (s_av_cpu_io_readdata_o),
    .s_av_waitrequest_o   (s_av_cpu_io_waitrequest_o),
    .s_av_readdatavalid_o (s_av_cpu_io_readdatavalid_o));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_uart_io
   (.wbm_adr_i (wb_m2s_resize_uart_io_adr),
    .wbm_dat_i (wb_m2s_resize_uart_io_dat),
    .wbm_sel_i (wb_m2s_resize_uart_io_sel),
    .wbm_we_i  (wb_m2s_resize_uart_io_we),
    .wbm_cyc_i (wb_m2s_resize_uart_io_cyc),
    .wbm_stb_i (wb_m2s_resize_uart_io_stb),
    .wbm_cti_i (wb_m2s_resize_uart_io_cti),
    .wbm_bte_i (wb_m2s_resize_uart_io_bte),
    .wbm_dat_o (wb_s2m_resize_uart_io_dat),
    .wbm_ack_o (wb_s2m_resize_uart_io_ack),
    .wbm_err_o (wb_s2m_resize_uart_io_err),
    .wbm_rty_o (wb_s2m_resize_uart_io_rty),
    .wbs_adr_o (wb_uart_io_adr_o),
    .wbs_dat_o (wb_uart_io_dat_o),
    .wbs_we_o  (wb_uart_io_we_o),
    .wbs_cyc_o (wb_uart_io_cyc_o),
    .wbs_stb_o (wb_uart_io_stb_o),
    .wbs_cti_o (wb_uart_io_cti_o),
    .wbs_bte_o (wb_uart_io_bte_o),
    .wbs_dat_i (wb_uart_io_dat_i),
    .wbs_ack_i (wb_uart_io_ack_i),
    .wbs_err_i (wb_uart_io_err_i),
    .wbs_rty_i (wb_uart_io_rty_i));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_post_io
   (.wbm_adr_i (wb_m2s_resize_post_io_adr),
    .wbm_dat_i (wb_m2s_resize_post_io_dat),
    .wbm_sel_i (wb_m2s_resize_post_io_sel),
    .wbm_we_i  (wb_m2s_resize_post_io_we),
    .wbm_cyc_i (wb_m2s_resize_post_io_cyc),
    .wbm_stb_i (wb_m2s_resize_post_io_stb),
    .wbm_cti_i (wb_m2s_resize_post_io_cti),
    .wbm_bte_i (wb_m2s_resize_post_io_bte),
    .wbm_dat_o (wb_s2m_resize_post_io_dat),
    .wbm_ack_o (wb_s2m_resize_post_io_ack),
    .wbm_err_o (wb_s2m_resize_post_io_err),
    .wbm_rty_o (wb_s2m_resize_post_io_rty),
    .wbs_adr_o (wb_post_io_adr_o),
    .wbs_dat_o (wb_post_io_dat_o),
    .wbs_we_o  (wb_post_io_we_o),
    .wbs_cyc_o (wb_post_io_cyc_o),
    .wbs_stb_o (wb_post_io_stb_o),
    .wbs_cti_o (wb_post_io_cti_o),
    .wbs_bte_o (wb_post_io_bte_o),
    .wbs_dat_i (wb_post_io_dat_i),
    .wbs_ack_i (wb_post_io_ack_i),
    .wbs_err_i (wb_post_io_err_i),
    .wbs_rty_i (wb_post_io_rty_i));

endmodule
